# Generated by Django 5.2.9 on 2026-01-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Static/images')),
                ('head', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
