# Generated by Django 5.2.9 on 2026-01-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Static/images')),
                ('name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
            ],
        ),
    ]
