# Generated by Django 5.2.9 on 2026-01-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Static/images')),
                ('head', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
