# Generated by Django 5.2.15 on 2026-07-29 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_attendance_bmirecord_bodymetrics_gymclass_newsletter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('author', models.CharField(default='Admin', max_length=50)),
                ('category', models.CharField(choices=[('Fitness', 'Fitness'), ('Workout', 'Workout'), ('Nutrition', 'Nutrition'), ('Motivation', 'Motivation')], default='Fitness', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Static/images')),
                ('snippet', models.TextField(help_text='Short description for list view')),
                ('content', models.TextField(help_text='Full article content')),
                ('read_time', models.CharField(default='5 min read', max_length=20)),
                ('comments_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='flaticon-034-stationary-bike', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('workout', 'Workout'), ('fitness', 'Fitness'), ('yoga', 'Yoga'), ('boxing', 'Boxing'), ('equipment', 'Equipment')], default='workout', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Static/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='about',
            name='experience_years',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='about',
            name='video_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='features_list',
            field=models.TextField(default='Free riding, Unlimited equipments, Personal trainer, Weight loss classes, No time restriction', help_text='Comma-separated features list'),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='period',
            field=models.CharField(default='SINGLE CLASS', max_length=50),
        ),
        migrations.AddField(
            model_name='services',
            name='icon_class',
            field=models.CharField(default='flaticon-002-dumbell', max_length=50),
        ),
        migrations.AddField(
            model_name='services',
            name='tag',
            field=models.CharField(default='FITNESS', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='facebook',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='instagram',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='twitter',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='head',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Static/images'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='membership',
            name='price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='services',
            name='head',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Static/images'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Static/images'),
        ),
    ]
