# Generated by Django 5.2.15 on 2026-09-18 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_attendance_user_bmirecord_user_bodymetrics_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='gym_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='myapp.gymclass'),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='assigned_trainer',
            field=models.ForeignKey(blank=True, help_text='Trainer (team member) this class is assigned to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='myapp.team'),
        ),
    ]
